"""
Django settings for fundval project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from .config import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get('debug', True)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'django_celery_beat',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fundval.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fundval.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_type = config.get('db_type', 'sqlite')
if db_type == 'postgresql':
    db_config = config.get('db_config', {})
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', db_config.get('name', 'fundval')),
            'USER': os.environ.get('POSTGRES_USER', db_config.get('user', 'fundval')),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', db_config.get('password', 'fundval')),
            'HOST': os.environ.get('POSTGRES_HOST', db_config.get('host', 'localhost')),
            'PORT': os.environ.get('POSTGRES_PORT', db_config.get('port', 5432)),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 前端构建文件目录
FRONTEND_BUILD_DIR = BASE_DIR.parent / 'frontend' / 'dist'

STATICFILES_DIRS = [
    FRONTEND_BUILD_DIR,
] if FRONTEND_BUILD_DIR.exists() else []

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS 配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境，生产环境需要配置白名单
CORS_ALLOW_CREDENTIALS = True

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# JWT 配置
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Celery 配置
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_CACHE_BACKEND = 'django-cache'  # 使用 Django 缓存
CELERY_TIMEZONE = 'Asia/Shanghai'  # 时区设置
CELERY_TASK_TRACK_STARTED = True  # 跟踪任务开始状态
CELERY_TASK_TIME_LIMIT = 30 * 60  # 任务超时时间：30 分钟
CELERY_ACCEPT_CONTENT = ['json']  # 接受的内容类型
CELERY_TASK_SERIALIZER = 'json'  # 任务序列化格式
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化格式

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'capture-estimate-snapshot': {
        'task': 'api.tasks.capture_estimate_snapshot',
        'schedule': crontab(minute=5, hour=15),  # 每天 15:05，任务内判断交易日
    },
    'audit-accuracy-task': {
        'task': 'api.tasks.audit_accuracy',
        'schedule': crontab(minute=0, hour=23),  # 每天 23:00，任务内判断交易日
    },
    'update-fund-nav-task': {
        'task': 'api.tasks.update_fund_nav',
        'schedule': crontab(minute=30, hour=22),  # 每天 22:30
    },
    'update-fund-today-nav-task': {
        'task': 'api.tasks.update_fund_today_nav',
        'schedule': crontab(minute=30, hour='21,23'),  # 21:30 和 23:00
    },
    'sync-all-fund-list-night': {
        'task': 'api.tasks.sync_funds',
        'schedule': crontab(minute=5, hour=20),  # 每天 20:05 全量刷新基金基础列表
    },
    'sync-all-fund-nav-history-and-facts-night': {
        'task': 'api.tasks.sync_all_fund_nav_history_and_facts',
        'schedule': crontab(minute=10, hour=22),  # 每天 22:10 同步前 2000 只基金净值和日事实
        'kwargs': {'days': 7, 'batch_size': 500, 'limit': 2000},
    },
    'sync-all-fund-profiles-and-holdings-night': {
        'task': 'api.tasks.sync_all_fund_profiles_and_holdings',
        'schedule': crontab(minute=20, hour=23),  # 每天 23:20 同步前 2000 只基金资料、规模、公司、板块配置和披露持仓
        'kwargs': {'batch_size': 300, 'limit': 2000, 'sync_holdings': True},
    },
    'sync-active-fund-nav-history-and-facts': {
        'task': 'api.tasks.sync_active_fund_nav_history_and_facts',
        'schedule': crontab(minute=45, hour=22),  # 每天 22:45 增量同步活跃基金净值和日事实
        'kwargs': {'limit': 300, 'days': 21},
    },
    'sync-active-fund-profiles-and-holdings': {
        'task': 'api.tasks.sync_active_fund_profiles_and_holdings',
        'schedule': crontab(minute=20, hour=20),  # 每天 20:20 同步腾讯资料和披露持仓
        'kwargs': {'limit': 300},
    },
    'sync-top-fund-rankings-afternoon': {
        'task': 'api.tasks.sync_top_fund_rankings_task',
        'schedule': crontab(minute=0, hour=14),  # 每天 14:00 同步盘中各周期前 500 名基金排行
        'kwargs': {'limit': 500, 'sync_profiles_limit': 500},
    },
    'sync-top-fund-rankings-intraday-10m': {
        'task': 'api.tasks.sync_top_fund_rankings_intraday_task',
        'schedule': crontab(minute='*/10', hour='9-14'),  # 交易时段每 10 分钟同步前 1000 名基金排行
        'kwargs': {'limit': 1000, 'sync_profiles_limit': 1000},
    },
    'sync-top-fund-intraday-estimates-10m': {
        'task': 'api.tasks.sync_top_fund_intraday_estimates_task',
        'schedule': crontab(minute='2-59/10', hour='9-14'),  # 交易时段每 10 分钟刷新前 1000 名基金今日估值涨幅
        'kwargs': {'limit': 1000, 'source_name': 'eastmoney'},
    },
    'sync-top-fund-rankings-close': {
        'task': 'api.tasks.sync_top_fund_rankings_task',
        'schedule': crontab(minute=10, hour=15),  # 每天 15:10 收盘后同步各周期前 500 名基金排行
        'kwargs': {'limit': 500, 'sync_profiles_limit': 500},
    },
    'sync-top-fund-rankings-night': {
        'task': 'api.tasks.sync_top_fund_rankings_task',
        'schedule': crontab(minute=10, hour=21),  # 每天 21:10 同步各周期前 500 名基金排行
        'kwargs': {'limit': 500, 'sync_profiles_limit': 500},
    },
    'sync-ranked-fund-basic-profiles': {
        'task': 'api.tasks.sync_ranked_fund_basic_profiles_task',
        'schedule': crontab(minute=40, hour=21),  # 每天 21:40 补齐排行基金基础资料和基金公司
        'kwargs': {'limit': 1000},
    },
    'sync-fund-sector-market-intraday': {
        'task': 'api.tasks.sync_fund_sector_market_snapshots_task',
        'schedule': crontab(minute='*/5', hour='9-14'),  # 盘中每 5 分钟拉取市场板块涨跌
        'kwargs': {'is_close_snapshot': False},
    },
    'sync-fund-sector-market-close': {
        'task': 'api.tasks.sync_fund_sector_market_snapshots_task',
        'schedule': crontab(minute=5, hour=15),  # 盘后保留当天最后一包板块涨跌快照
        'kwargs': {'is_close_snapshot': True},
    },
    'analyze-fund-sector-rotation-close': {
        'task': 'api.tasks.analyze_fund_sector_rotation_task',
        'schedule': crontab(minute=12, hour=15),  # 盘后板块快照落库后生成基金归属板块分析
        'kwargs': {'board_code': 'industry', 'close_only': True, 'page_size': 500},
    },
    'backfill-fund-daily-facts-weekly': {
        'task': 'api.tasks.backfill_fund_daily_facts_task',
        'schedule': crontab(minute=30, hour=7, day_of_week=6),  # 周六 07:30 修复历史事实缺口
        'kwargs': {'limit': 1000},
    },
    'check-notification-rules': {
        'task': 'api.tasks.check_notification_rules',
        'schedule': crontab(minute='*/5'),  # 每 5 分钟
    },
    'capture-intraday-snapshots': {
        'task': 'api.tasks.capture_intraday_snapshots',
        'schedule': crontab(minute='*/5', hour='9-14'),  # 交易时段每5分钟
    },
    'capture-intraday-close': {
        'task': 'api.tasks.capture_intraday_snapshots',
        'schedule': crontab(minute=5, hour=15),  # 15:05 收盘最后一抓
    },
    'generate-weekly-report': {
        'task': 'api.tasks.generate_investment_reports',
        'schedule': crontab(minute=0, hour=9, day_of_week=1),  # 每周一 9:00
    },
    'generate-monthly-report': {
        'task': 'api.tasks.generate_investment_reports',
        'schedule': crontab(minute=0, hour=9, day_of_month=1),  # 每月 1 日 9:00
    },
    'sync-quarterly-fund-holdings-and-evaluations': {
        'task': 'api.tasks.sync_quarterly_fund_holdings_and_evaluations_task',
        'schedule': crontab(minute=30, hour=8, day_of_month=1, month_of_year='1,4,7,10'),
        'kwargs': {'limit': 2000, 'source_name': 'tencent_fund', 'window_days': 370},
    },
}
