# Generated by Codex on 2026-06-21

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_widen_report_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '基金公司',
                'verbose_name_plural': '基金公司',
                'db_table': 'fund_company',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='FundHoldingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(help_text='披露/快照日期')),
                ('source', models.CharField(default='eastmoney', max_length=50)),
                ('target_code', models.CharField(blank=True, max_length=32, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_snapshots', to='api.fund')),
            ],
            options={
                'verbose_name': '基金持仓快照',
                'verbose_name_plural': '基金持仓快照',
                'db_table': 'fund_holding_snapshot',
                'ordering': ['-report_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('manager_name', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='api.fundcompany')),
            ],
            options={
                'verbose_name': '基金经理',
                'verbose_name_plural': '基金经理',
                'db_table': 'fund_manager',
                'ordering': ['manager_name'],
            },
        ),
        migrations.CreateModel(
            name='FundHoldingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holding_type', models.CharField(default='stock', max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('asset_name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('contribution', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.fundholdingsnapshot')),
            ],
            options={
                'verbose_name': '基金持仓明细',
                'verbose_name_plural': '基金持仓明细',
                'db_table': 'fund_holding_item',
                'ordering': ['sort_order', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='FundManagerTenure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_tenures', to='api.fund')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures', to='api.fundmanager')),
            ],
            options={
                'verbose_name': '基金经理任职',
                'verbose_name_plural': '基金经理任职',
                'db_table': 'fund_manager_tenure',
            },
        ),
        migrations.AddIndex(
            model_name='fundholdingsnapshot',
            index=models.Index(fields=['fund', '-report_date'], name='api_fund_ho_fund_id_8f3b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundholdingsnapshot',
            index=models.Index(fields=['report_date', 'source'], name='api_fund_ho_report__d6f29d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundholdingsnapshot',
            unique_together={('fund', 'report_date', 'source', 'target_code')},
        ),
        migrations.AddIndex(
            model_name='fundholdingitem',
            index=models.Index(fields=['asset_code'], name='api_fund_ho_asset_c_8cb824_idx'),
        ),
        migrations.AddIndex(
            model_name='fundholdingitem',
            index=models.Index(fields=['holding_type'], name='api_fund_ho_holding_ee263d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundholdingitem',
            unique_together={('snapshot', 'asset_code', 'holding_type')},
        ),
        migrations.AddIndex(
            model_name='fundmanagertenure',
            index=models.Index(fields=['fund', 'end_date'], name='api_fund_ma_fund_id_34f506_idx'),
        ),
        migrations.AddIndex(
            model_name='fundmanagertenure',
            index=models.Index(fields=['manager', 'start_date'], name='api_fund_ma_manager_f3ba3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundmanagertenure',
            unique_together={('fund', 'manager', 'start_date')},
        ),
    ]
