# Generated by Codex on 2026-06-21

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_fund_company_manager_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='api.fundcompany'),
        ),
        migrations.AddField(
            model_name='fund',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='inception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_size',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='基金规模，单位亿元', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_size_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='tracking_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='purchase_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='redemption_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='custody_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='profile_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='profile_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='FundDailyFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_date', models.DateField()),
                ('unit_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('accumulated_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('daily_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estimate_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estimate_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estimate_time', models.DateTimeField(blank=True, null=True)),
                ('estimate_error_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('source', models.CharField(default='system', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_facts', to='api.fund')),
            ],
            options={
                'verbose_name': '基金每日事实',
                'verbose_name_plural': '基金每日事实',
                'db_table': 'fund_daily_fact',
                'ordering': ['-trade_date'],
            },
        ),
        migrations.AddIndex(
            model_name='funddailyfact',
            index=models.Index(fields=['fund', '-trade_date'], name='api_fund_da_fund_id_b8f499_idx'),
        ),
        migrations.AddIndex(
            model_name='funddailyfact',
            index=models.Index(fields=['trade_date'], name='api_fund_da_trade_d_7f8544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funddailyfact',
            unique_together={('fund', 'trade_date')},
        ),
    ]
