# Generated by Codex on 2026-06-21

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fund_profile_daily_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('allocation_type', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(default='tencent_fund', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_snapshots', to='api.fund')),
            ],
            options={
                'verbose_name': '基金板块配置快照',
                'verbose_name_plural': '基金板块配置快照',
                'db_table': 'fund_allocation_snapshot',
                'ordering': ['-report_date', 'allocation_type', '-ratio'],
            },
        ),
        migrations.CreateModel(
            name='FundPerformanceRankSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_date', models.DateField()),
                ('period', models.CharField(db_index=True, max_length=32)),
                ('growth', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('quartile', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='tencent_fund', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_rank_snapshots', to='api.fund')),
            ],
            options={
                'verbose_name': '基金业绩排行快照',
                'verbose_name_plural': '基金业绩排行快照',
                'db_table': 'fund_performance_rank_snapshot',
                'ordering': ['-rank_date', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='fundallocationsnapshot',
            index=models.Index(fields=['fund', '-report_date'], name='api_fund_al_fund_id_ee056e_idx'),
        ),
        migrations.AddIndex(
            model_name='fundallocationsnapshot',
            index=models.Index(fields=['allocation_type', 'name'], name='api_fund_al_allocat_36a3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fundperformanceranksnapshot',
            index=models.Index(fields=['fund', '-rank_date'], name='api_fund_pe_fund_id_08a2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='fundperformanceranksnapshot',
            index=models.Index(fields=['period', 'rank_date'], name='api_fund_pe_period_6cc3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fundperformanceranksnapshot',
            index=models.Index(fields=['rank_date', 'rank'], name='api_fund_pe_rank_da_2bd5bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundallocationsnapshot',
            unique_together={('fund', 'report_date', 'allocation_type', 'name', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='fundperformanceranksnapshot',
            unique_together={('fund', 'rank_date', 'period', 'source')},
        ),
    ]
