# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fund_sector_market_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundperformanceranksnapshot',
            name='rank_type',
            field=models.CharField(db_index=True, default='performance', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='fundperformanceranksnapshot',
            unique_together={('fund', 'rank_type', 'rank_date', 'period', 'source')},
        ),
        migrations.AddIndex(
            model_name='fundperformanceranksnapshot',
            index=models.Index(fields=['rank_type', 'period', 'rank_date'], name='api_fund_pe_rank_ty_1f9a2b_idx'),
        ),
    ]
